##Numpy
- numerical python
- it works as creating arrays and mathematical operation and statistical perations


In [2]:
import numpy as np

In [3]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [4]:
len(dir(np))

620

In [5]:
##craeting an array
a1=np.array([1,2,3,4,5])

In [6]:
a1

array([1, 2, 3, 4, 5])

In [7]:
a.ndim

NameError: name 'a' is not defined

In [8]:
a1.ndim

1

In [9]:
a1.shape

(5,)

In [10]:
a1.size

5

In [12]:
a2=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [13]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
a2.ndim


2

In [15]:
a2.size

10

In [17]:
a2.shape

(2, 5)

In [19]:
a3=np.arange(1,31)

In [20]:
a3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [21]:
a3.ndim

1

In [22]:
a3.size

30

In [23]:
a3.shape

(30,)

In [25]:
a3.reshape(2,15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [27]:
a3.reshape(2,15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [29]:
a3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [37]:
a4=a3.reshape(3,10)

In [35]:
a4=a3

In [38]:
a4

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [47]:
a4[1:2,]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [50]:
a4=a4.reshape(5,6)

In [51]:
a4

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [61]:
a4[1:2]

array([[ 7,  8,  9, 10, 11, 12]])

In [59]:
a4

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [62]:
a4[1:2,1:10:2]

array([[ 8, 10, 12]])

In [63]:
a5=a4.reshape(6,5)

In [64]:
a5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [65]:
a5[3:6:2,2:5:2]

array([[18, 20],
       [28, 30]])

In [66]:
a5[3:5:2,2:5:2]

array([[18, 20]])

In [67]:
np.random.random()

0.8016482013626729

In [68]:
np.random.rand()

0.8169414465524975

In [73]:
np.random.randint(1,10,2)

array([2, 4])

In [95]:
a5=np.random.randint(1,1000,100)
while a5<=100:
    if a5%2==0:
        print(a5)
    

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [83]:
a5

array([885, 972, 801, 776, 883, 525, 185, 206, 828, 837, 424, 262, 298,
       700, 428, 951, 664, 870,  11, 436, 629, 356, 602, 454, 318, 685,
       763, 453, 757, 369, 301, 365, 159, 419, 975, 416, 536, 183, 538,
       298, 585, 788, 522, 499, 683, 893,  50, 630,  50, 832, 857, 973,
       805, 887, 385, 657, 370, 463, 860, 548, 731, 207, 642, 552, 776,
       270, 794, 268,  23, 818, 822,   2,  46, 411, 227, 514,   4, 847,
       442, 968,  99, 412, 786, 273, 921, 197, 604, 786, 477, 418, 654,
       445, 948, 739, 371, 363, 547, 958,  64, 556])

In [85]:
a5[a5%2==0]

array([972, 776, 206, 828, 424, 262, 298, 700, 428, 664, 870, 436, 356,
       602, 454, 318, 416, 536, 538, 298, 788, 522,  50, 630,  50, 832,
       370, 860, 548, 642, 552, 776, 270, 794, 268, 818, 822,   2,  46,
       514,   4, 442, 968, 412, 786, 604, 786, 418, 654, 948, 958,  64,
       556])

In [3]:
import numpy as np
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
np.zeros((5,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [6]:
np.hstack((a3,a4))

NameError: name 'a3' is not defined

In [7]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [8]:
np.random.randint(91,1000,100)

array([159, 910, 430, 985, 470, 572, 188, 891, 295, 407, 312, 236, 311,
       365, 930, 734, 540, 964, 425, 429, 861, 251, 240, 879, 876, 958,
       475, 944, 580, 550, 901,  96, 125, 662, 143, 140, 913, 983, 680,
       885, 757, 202, 562, 151, 287, 191, 558, 431, 404, 735, 230, 121,
       650, 483, 580, 290, 211, 852, 436, 247, 518, 222, 231, 163, 928,
       658, 278, 992, 339, 913, 388, 985, 746, 965, 730, 140, 491, 958,
       990, 862, 911, 548, 589, 553, 262, 544, 107, 992, 634, 939, 587,
       217, 271, 703, 260, 191, 421, 244, 664, 325])

In [9]:
a6=np.eye(4,5)

In [10]:
np.diagonal(a6)

array([1., 1., 1., 1.])

In [11]:
a6

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [13]:
a7=np.arange(1,31)

In [14]:
a7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [15]:
a8=a7.reshape(6,5)

In [16]:
a8

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [17]:
a8.diagonal()

array([ 1,  7, 13, 19, 25])

In [19]:
a8.max()

30

In [21]:
a8.min()

1

In [22]:
a8.mean()

15.5

In [23]:
a8.std()

8.65544144839919

In [28]:
a8.cumsum()

array([   1,    4,   10,   20,   35,   56,   84,  120,  165,  220,  286,
        364,  455,  560,  680,  816,  969, 1140, 1330, 1540, 1771, 2024,
       2300, 2600, 2925, 3276, 3654, 4060, 4495, 4960], dtype=int32)

In [31]:
a8

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190, 210, 231, 253, 276, 300, 325, 351,
       378, 406, 435, 465], dtype=int32)

In [33]:
a8.argmax()

29

In [34]:
a8.argmin()

0

In [35]:
a8.transpose()

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190, 210, 231, 253, 276, 300, 325, 351,
       378, 406, 435, 465], dtype=int32)

In [36]:
a8=a8.reshape(6,5)

In [37]:
a8

array([[  1,   3,   6,  10,  15],
       [ 21,  28,  36,  45,  55],
       [ 66,  78,  91, 105, 120],
       [136, 153, 171, 190, 210],
       [231, 253, 276, 300, 325],
       [351, 378, 406, 435, 465]], dtype=int32)

In [38]:
n=np.array([1,2,3])

In [39]:
n

array([1, 2, 3])

In [40]:
np.save("array n",n)

In [42]:
np.median(a8)

128.0

In [44]:
np.percentile(a7,5)

2.45

In [45]:
np.tan(a8)

array([[ 1.55740772e+00, -1.42546543e-01, -2.91006191e-01,
         6.48360827e-01, -8.55993401e-01],
       [-1.52749853e+00, -2.81429605e-01,  7.75047091e+00,
         1.61977519e+00, -4.51830879e+01],
       [ 2.65605178e-02, -5.99179998e-01, -1.06587872e-01,
         4.02780176e+00,  7.13123010e-01],
       [ 1.29040156e+00, -1.36361502e+00,  4.54006019e+00,
         1.50482062e+01, -5.29166692e-01],
       [-1.07286365e+01, -9.79006006e+00, -4.95639983e-01,
         4.52447421e+01,  6.40659836e+00],
       [-1.15775073e+00,  1.58825926e+00,  9.03140880e-01,
         9.00612944e+00,  4.43162459e-02]])

In [46]:
np.sin(a8)

array([[ 0.84147098,  0.14112001, -0.2794155 , -0.54402111,  0.65028784],
       [ 0.83665564,  0.27090579, -0.99177885,  0.85090352, -0.99975517],
       [-0.02655115,  0.51397846,  0.10598751, -0.97053528,  0.58061118],
       [-0.79043321,  0.80640058,  0.97659087,  0.99779928,  0.46771852],
       [-0.99568419,  0.99482373, -0.44408566, -0.99975584, -0.98803627],
       [-0.75678279,  0.84623647, -0.67025155,  0.99389198,  0.04427279]])

In [50]:
np.cos(a8)

array([[ 0.54030231, -0.9899925 ,  0.96017029, -0.83907153, -0.75968791],
       [-0.54772926, -0.96260587, -0.12796369,  0.52532199,  0.02212676],
       [-0.99964746, -0.85780309, -0.99436746, -0.24095905,  0.81418097],
       [-0.61254824, -0.59136968,  0.21510527,  0.06630686, -0.88387747],
       [ 0.09280622, -0.10161569,  0.89598433, -0.02209662, -0.15422167],
       [ 0.65366643,  0.53280751, -0.74213399,  0.11035728,  0.99901948]])

In [51]:
np.tanh(a8)

array([[0.76159416, 0.99505475, 0.99998771, 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ]])

In [52]:
np.cosh(a8)

array([[1.54308063e+000, 1.00676620e+001, 2.01715636e+002,
        1.10132329e+004, 1.63450869e+006],
       [6.59407867e+008, 7.23128532e+011, 2.15561577e+015,
        1.74671355e+019, 3.84739263e+023],
       [2.30359332e+028, 3.74920850e+033, 1.65870005e+039,
        1.99475979e+045, 6.52090439e+051],
       [5.79454771e+058, 1.39967026e+066, 9.19023062e+073,
        1.64029351e+082, 7.95813320e+090],
       [1.04953113e+100, 3.76247762e+109, 3.66646049e+119,
        9.71213198e+129, 6.99321085e+140],
       [1.36877843e+152, 7.28256155e+163, 1.05324561e+176,
        4.14066058e+188, 4.42490641e+201]])

In [53]:
np.sinh(a8)

array([[1.17520119e+000, 1.00178749e+001, 2.01713157e+002,
        1.10132329e+004, 1.63450869e+006],
       [6.59407867e+008, 7.23128532e+011, 2.15561577e+015,
        1.74671355e+019, 3.84739263e+023],
       [2.30359332e+028, 3.74920850e+033, 1.65870005e+039,
        1.99475979e+045, 6.52090439e+051],
       [5.79454771e+058, 1.39967026e+066, 9.19023062e+073,
        1.64029351e+082, 7.95813320e+090],
       [1.04953113e+100, 3.76247762e+109, 3.66646049e+119,
        9.71213198e+129, 6.99321085e+140],
       [1.36877843e+152, 7.28256155e+163, 1.05324561e+176,
        4.14066058e+188, 4.42490641e+201]])

In [54]:
a9=np.arange(1,101)

In [55]:
a9

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [62]:
a -> 65
;;;
..
..
Z -> 50

SyntaxError: invalid syntax (<ipython-input-62-ba67eb366177>, line 1)

In [66]:
import time,webbrowser
browsers=3
count=0
while count<=3:
    time.sleep(10)
    if count==1:
      webbrowser.open("http://apssdc.in")
    elif count==2:
      webbrowser.open("http://nrtec.in")
    elif count==3:
        webbrowser.open("htttp.//google.com")
    count+=1